import { env } from "../config/env.js"
import { areaRepository } from "../infrastructure/db/areaRepository.js"
import { usuarioRepository } from "../infrastructure/db/usuarioRepository.js"
import { funcionarioRepository } from "../infrastructure/db/funcionarioRepository.js"
import { capacitacionRepository } from "../infrastructure/db/capacitacionRepository.js"
import { cursoRepository } from "../infrastructure/db/cursoRepository.js"
import { planificadorRepository } from "../infrastructure/db/planificadorRepository.js"
import { loteImportacionRepository } from "../infrastructure/db/loteImportacionRepository.js"
import { verificarJwt } from "../infrastructure/auth/supabaseJwtVerifier.js"
import { supabaseStorage } from "../infrastructure/storage/supabaseStorage.js"
import {
  abrirRegistro,
  abrirRegistroCurso,
  archivarCaso,
  asegurarUsuario,
  asignarRol,
  cambiarActivaArea,
  cambiarEstadoArea,
  cambiarEstadoUsuario,
  cerrarRegistro,
  cerrarRegistroCurso,
  confirmarImportacionParcial,
  crearArea,
  crearCapacitacion,
  crearCapacitacionPlaneada,
  crearCurso,
  crearEmpleado,
  crearExperiencia,
  crearFamiliar,
  crearFormacion,
  crearLeccionCurso,
  crearModuloCurso,
  crearUrlSubidaFoto,
  devolverCasoAArea,
  editarCapacitacion,
  editarCapacitacionPlaneada,
  editarContractual,
  editarCurso,
  editarEmpleado,
  editarLeccionCurso,
  editarModuloCurso,
  eliminarCapacitacionPlaneada,
  eliminarExperiencia,
  eliminarFamiliar,
  eliminarFormacion,
  eliminarLeccionCurso,
  eliminarModuloCurso,
  exportarArchivo,
  exportarAsistencias,
  finalizarContrato,
  generarLiquidacion,
  guardarFoto,
  guardarPersonales,
  guardarSalarial,
  ingresarCurso,
  listarAreas,
  listarArchivo,
  listarCapacitaciones,
  listarCapacitacionesPlaneadas,
  listarCursos,
  listarEmpleados,
  listarFuncionarios,
  listarGestionArea,
  listarInscritosCurso,
  listarUsuarios,
  marcarLeccionCompletadaCurso,
  moverArea,
  moverLeccionCurso,
  moverModuloCurso,
  obtenerDetalle,
  obtenerCapacitacionPublica,
  obtenerCursoPublico,
  obtenerDetalleCapacitacion,
  obtenerDetalleCurso,
  obtenerEmpleado,
  obtenerExpediente,
  obtenerExpedientePersonal,
  obtenerMatriz,
  obtenerMetricas,
  obtenerUrlFoto,
  previsualizarImportacionDesvinculaciones,
  registrarAsistenciaPublica,
  registrarLiquidacion,
  registrarNovedad,
  renombrarArea,
} from "../application/index.js"
import { crearRequireAuth } from "./middleware/requireAuth.js"

/**
 * Composition root: inyecta los repos Drizzle en los casos de uso y arma el
 * `requireAuth` con el verificador JWT + autoregistro. Es el único lugar que
 * conoce las implementaciones concretas; controllers y routes solo ven las
 * funciones ya cableadas.
 */
const asegurar = asegurarUsuario({
  repo: usuarioRepository,
  superadminEmail: env.SUPERADMIN_EMAIL,
  dominioPermitido: env.DOMINIO_PERMITIDO,
})

export const casos = {
  listarFuncionarios: listarFuncionarios({ repo: funcionarioRepository }),
  obtenerMatriz: obtenerMatriz({ repo: funcionarioRepository }),
  obtenerDetalle: obtenerDetalle({ repo: funcionarioRepository }),
  cambiarEstadoArea: cambiarEstadoArea({ repo: funcionarioRepository }),
  devolverCasoAArea: devolverCasoAArea({ repo: funcionarioRepository }),
  archivarCaso: archivarCaso({ repo: funcionarioRepository }),
  generarLiquidacion: generarLiquidacion({ repo: funcionarioRepository }),
  registrarLiquidacion: registrarLiquidacion({ repo: funcionarioRepository }),
  listarGestionArea: listarGestionArea({ repo: funcionarioRepository }),
  obtenerMetricas: obtenerMetricas({ repo: funcionarioRepository }),
  listarArchivo: listarArchivo({ repo: funcionarioRepository }),
  obtenerExpediente: obtenerExpediente({ repo: funcionarioRepository }),
  exportarArchivo: exportarArchivo({ repo: funcionarioRepository }),
  listarAreas: listarAreas({ repo: areaRepository }),
  crearArea: crearArea({ repo: areaRepository }),
  renombrarArea: renombrarArea({ repo: areaRepository }),
  moverArea: moverArea({ repo: areaRepository }),
  cambiarActivaArea: cambiarActivaArea({ repo: areaRepository }),
  asignarRol: asignarRol({ repo: usuarioRepository }),
  cambiarEstadoUsuario: cambiarEstadoUsuario({ repo: usuarioRepository }),
  listarUsuarios: listarUsuarios({ repo: usuarioRepository }),
  listarCapacitaciones: listarCapacitaciones({ repo: capacitacionRepository }),
  crearCapacitacion: crearCapacitacion({ repo: capacitacionRepository }),
  obtenerDetalleCapacitacion: obtenerDetalleCapacitacion({ repo: capacitacionRepository }),
  obtenerInfoPublica: obtenerCapacitacionPublica({ repo: capacitacionRepository }),
  editarCapacitacion: editarCapacitacion({ repo: capacitacionRepository }),
  abrirRegistro: abrirRegistro({ repo: capacitacionRepository }),
  cerrarRegistro: cerrarRegistro({ repo: capacitacionRepository }),
  exportarAsistencias: exportarAsistencias({ repo: capacitacionRepository }),
  registrarAsistenciaPublica: registrarAsistenciaPublica({ repo: capacitacionRepository }),
  listarCursos: listarCursos({ repo: cursoRepository }),
  crearCurso: crearCurso({ repo: cursoRepository }),
  obtenerDetalleCurso: obtenerDetalleCurso({ repo: cursoRepository }),
  editarCurso: editarCurso({ repo: cursoRepository }),
  abrirRegistroCurso: abrirRegistroCurso({ repo: cursoRepository }),
  cerrarRegistroCurso: cerrarRegistroCurso({ repo: cursoRepository }),
  crearModuloCurso: crearModuloCurso({ repo: cursoRepository }),
  editarModuloCurso: editarModuloCurso({ repo: cursoRepository }),
  moverModuloCurso: moverModuloCurso({ repo: cursoRepository }),
  eliminarModuloCurso: eliminarModuloCurso({ repo: cursoRepository }),
  crearLeccionCurso: crearLeccionCurso({ repo: cursoRepository }),
  editarLeccionCurso: editarLeccionCurso({ repo: cursoRepository }),
  moverLeccionCurso: moverLeccionCurso({ repo: cursoRepository }),
  eliminarLeccionCurso: eliminarLeccionCurso({ repo: cursoRepository }),
  listarInscritosCurso: listarInscritosCurso({ repo: cursoRepository }),
  obtenerCursoPublico: obtenerCursoPublico({ repo: cursoRepository }),
  ingresarCurso: ingresarCurso({ repo: cursoRepository }),
  marcarLeccionCompletadaCurso: marcarLeccionCompletadaCurso({ repo: cursoRepository }),
  crearEmpleado: crearEmpleado({ repo: funcionarioRepository }),
  editarEmpleado: editarEmpleado({ repo: funcionarioRepository }),
  finalizarContrato: finalizarContrato({ repo: funcionarioRepository }),
  registrarNovedad: registrarNovedad({ repo: funcionarioRepository }),
  listarEmpleados: listarEmpleados({ repo: funcionarioRepository }),
  obtenerEmpleado: obtenerEmpleado({ repo: funcionarioRepository }),
  obtenerExpedientePersonal: obtenerExpedientePersonal({ repo: funcionarioRepository }),
  guardarPersonales: guardarPersonales({ repo: funcionarioRepository }),
  crearFamiliar: crearFamiliar({ repo: funcionarioRepository }),
  eliminarFamiliar: eliminarFamiliar({ repo: funcionarioRepository }),
  crearFormacion: crearFormacion({ repo: funcionarioRepository }),
  eliminarFormacion: eliminarFormacion({ repo: funcionarioRepository }),
  crearExperiencia: crearExperiencia({ repo: funcionarioRepository }),
  eliminarExperiencia: eliminarExperiencia({ repo: funcionarioRepository }),
  guardarSalarial: guardarSalarial({ repo: funcionarioRepository }),
  editarContractual: editarContractual({ repo: funcionarioRepository }),
  crearUrlSubidaFoto: crearUrlSubidaFoto({ storage: supabaseStorage }),
  guardarFoto: guardarFoto({ repo: funcionarioRepository }),
  obtenerUrlFoto: obtenerUrlFoto({ repo: funcionarioRepository, storage: supabaseStorage }),
  listarCapacitacionesPlaneadas: listarCapacitacionesPlaneadas({ repo: planificadorRepository }),
  crearCapacitacionPlaneada: crearCapacitacionPlaneada({ repo: planificadorRepository }),
  editarCapacitacionPlaneada: editarCapacitacionPlaneada({ repo: planificadorRepository }),
  eliminarCapacitacionPlaneada: eliminarCapacitacionPlaneada({ repo: planificadorRepository }),
  previsualizarImportacionDesvinculaciones: previsualizarImportacionDesvinculaciones({
    repo: loteImportacionRepository,
  }),
  confirmarImportacionParcial: confirmarImportacionParcial({ repo: loteImportacionRepository }),
}

export type Casos = typeof casos

export const requireAuth = crearRequireAuth({ verificar: verificarJwt, asegurar })
